/**
 * ExcitesmsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema';
import { Data, dataSchema } from './data';
import { Link, linkSchema } from './link';

export interface Data1 {
  currentPage: number;
  data: Data[];
  firstPageUrl: string;
  from: number;
  lastPage: number;
  lastPageUrl: string;
  links: Link[];
  nextPageUrl: string | null;
  path: string;
  perPage: number;
  prevPageUrl: string | null;
  to: number;
  total: number;
}

export const data1Schema: Schema<Data1> = object({
  currentPage: ['current_page', number()],
  data: ['data', array(lazy(() => dataSchema))],
  firstPageUrl: ['first_page_url', string()],
  from: ['from', number()],
  lastPage: ['last_page', number()],
  lastPageUrl: ['last_page_url', string()],
  links: ['links', array(lazy(() => linkSchema))],
  nextPageUrl: ['next_page_url', nullable(string())],
  path: ['path', string()],
  perPage: ['per_page', number()],
  prevPageUrl: ['prev_page_url', nullable(string())],
  to: ['to', number()],
  total: ['total', number()],
});
