/**
 * ExcitesmsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Data {
  uid: string;
  to: string;
  from: string;
  message: string;
  status: string;
  cost: string;
}

export const dataSchema: Schema<Data> = object({
  uid: ['uid', string()],
  to: ['to', string()],
  from: ['from', string()],
  message: ['message', string()],
  status: ['status', string()],
  cost: ['cost', string()],
});
