/**
 * ExcitesmsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SendSMSRequest {
  recipient: string;
  senderId: string;
  message: string;
}

export const sendSMSRequestSchema: Schema<SendSMSRequest> = object({
  recipient: ['recipient', string()],
  senderId: ['sender_id', string()],
  message: ['message', string()],
});
