/**
 * ExcitesmsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Data, dataSchema } from './data';

export interface SendSMS {
  status: string;
  message: string;
  data: Data;
}

export const sendSMSSchema: Schema<SendSMS> = object({
  status: ['status', string()],
  message: ['message', string()],
  data: ['data', lazy(() => dataSchema)],
});
